name: Run scripts
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-script: #name of the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Print out some information
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Checks out the repo so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      # Run the shellscripts
      - name: Run run.sh
        run: sh ./run.sh

      - name: Run print-list-of-files.sh
        run: sh ./print-list-of-files.sh

      # Print out the job status
      - run: echo "This job's status is ${{ job.status }}."
